### ISSUE TITLE
戦略画面の勢力メニューウインドウ

### ISSUE THREAD

**Issue by Yutaka-Sawada** [fluffySheepInX/WPF_Successor_001_to_Vahren#12]
戦略画面において右下に表示される勢力メニューのウインドウに
[領地数] と [ユニット数] を表示する方法が分かったので
参考までにコードを書いておきます。

ファイル UserControl005_StrategyMenu.xaml.cs の
DisplayPowerStatus 関数において値を設定してる部分
```
//領土数
{
    this.lblNameNumberSpot.Content = "";
}
//ユニット数
{
    this.lblNameNumberUnit.Content = "";
}
```
に Class データを参照するコードを追加します。
```
//領地数
{
    this.lblNameNumberSpot.Content = mainWindow.ClassGameStatus.SelectionPowerAndCity.ClassPower.ListMember.Count;
}
//ユニット数
{
    string select_NameTag = mainWindow.ClassGameStatus.SelectionPowerAndCity.ClassPower.NameTag;
    int unit_count = 0;
    var list_spot = mainWindow.ClassGameStatus.AllListSpot.Where(x => x.PowerNameTag == select_NameTag);
    foreach (var item_spot in list_spot)
    {
        foreach (var item_group in item_spot.UnitGroup)
        {
            unit_count += item_group.ListClassUnit.Count;
        }
    }
    this.lblNameNumberUnit.Content = unit_count;
}
```
という感じです。

あと、ヴァーレントゥーガでは「領土数」ではなく「領地数」と表記されてるので、
ファイル UserControl005_StrategyMenu.xaml の該当箇所を「領地数」に変えれば、
ヴァーレンと同じように表示されます。
まあ、意味は同じなんですが、表記揺れで、検索しにくくなるかもしれないので。

**Comment by fluffySheepInX** [comment]
コミットしました！表記も直しました！ありがとうございます！

**Comment by Yutaka-Sawada** [comment]
UserControl005_StrategyMenu.xaml.cs などにおいて、
コントロールから親ウインドウを参照する際に
```
var window = Application.Current.Properties["window"];
if (window == null)
{
    return;
}
var mainWindow = window as MainWindow;
if (mainWindow == null)
{
    return;
}
```
のようにして、プロパティに一度登録してから、その項目を探してます。

しかし、[ネットで調べた所](http://main.tinyjoker.net/Tech/CSharp/WPF/%A5%E6%A1%BC%A5%B6%A1%BC%A5%B3%A5%F3%A5%C8%A5%ED%A1%BC%A5%EB%A4%CE%BF%C6%A5%A6%A5%A3%A5%F3%A5%C9%A5%A6%A4%F2%C4%B4%A4%D9%A4%EB.html)、一個しかウインドウを使わないゲームなら
```
var mainWindow = (MainWindow)Application.Current.MainWindow;
```
として MainWindow を一発で取得できるようです。
こちらの方が単純でいいかもしれません。
