### ISSUE TITLE
マップファイルの仕様について

### ISSUE THREAD

**Issue by fluffySheepInX** [fluffySheepInX/WPF_Successor_001_to_Vahren#13]
頂いた指摘は以下の通り

～～～～～～～～～
タイルごとの
要素の個数をチェックできるのなら、
不要な項目は省略できた方が、
ファイル・サイズが小さくなります。

１個= field
２個= field*object
３個= field*object*unit
５個= field*object*unit*houkou*zinkei

みたいな感じに順番だけ決めておけば、
要素の個数で存在する値を読み込んで
存在しない値は自動的にnullにすればいい。

なお、防衛施設や退却位置などのように
unitの方向、unitの陣形
が不要な場合もあるから、
unitの名前
を先に記録した方が、省略しやすい。
～～～～～～～～～

**Comment by fluffySheepInX** [comment]
【フォーマット再考】
field(マップチップ名)
,object(建築物名)
,flagDefObject(ユニットが防衛施設か)
,flagESC(ユニットの退却位置か)
,unit
,direction(方向。flagDefObjectがTrueの時、省略)
,formation(陣形。flagDefObjectがTrueの時、省略)

**Comment by Yutaka-Sawada** [comment]
flagの使い道について考えてみました。


ヴァーレントゥーガまとめwiki の
spot 構造体（領地の設定） から転載
```
戦場マップの部隊配置について

「部隊チップ」と同名の構造体ユニットが配置されます。
すでに存在する人材ユニットならそれを配置し、そうでないなら新規作成されて配置されます。
新規作成されたユニットは戦闘イベント終了後に全削除されます。
「部隊チップ」には文字変数も指定できます。@を先頭につけると文字変数とみなされます。
```

`ユニットの識別名` 同名のunit/class構造体ユニットが配置されます

`@文字変数` @が接頭辞の文字列は文字変数と見なされます。代入スクリプトで防衛施設を変化できます

特殊な文字列
`@` 防衛部隊の位置。
`@@` 侵攻部隊の位置。
`@ESC@` 城兵の退却位置になります。


という風に、部隊チップは大まかに分類して３種類になります。
なので、flag を使うなら整数一個で分岐させたら良さそうです。（enum型でもいい）
flag = 0 なら「ユニットの識別名」として扱う。
flag = 1 なら「@文字変数」として扱う。
flag = 2 なら「特殊な文字列」として扱う。
みたいな感じです。種類はもっと細分化してもいいかも。

データの並び順としては最大で６個になります。
field(マップチップ名), object(建築物名), flag(部隊チップの種別), 部隊チップ, 方向, 陣形

部隊チップのデータをどう扱うかが事前に分かるから、処理を実装しやすそうです。

あと、ヴァーレンはobject（建築物チップ）の上に unit (部隊チップ) を配置できます。
（同じタイルに object と unit が重複可能）

**Comment by fluffySheepInX** [comment]
頂いた意見を元にマップフォーマットを改善しました（しています
ありがとうございます。

**Comment by fluffySheepInX** [comment]
完了しました。
