### ISSUE TITLE
勢力選択時に領地をクリックした際の不具合

### ISSUE THREAD

**Issue by Yutaka-Sawada** [fluffySheepInX/WPF_Successor_001_to_Vahren#3]
#### 勢力選択時に領地を右クリックすると出撃画面になる不具合

通常はマップを右クリックすると、前の画面に戻るんですが、領地を右クリックした時だけ、出撃画面になります。
どうやら、クリック・イベント内でゲーム状態を判断してないからのようです。

なので、修正方法は状況判定コードを追加するだけです。
```
private void ButtonSelectionCity_RightKeyDown(object sender, EventArgs e)
```
関数の最初の所
```
var cast = (Button)sender;
if (cast.Tag is not ClassPowerAndCity)
{
    return;
}
```
において、現在の状態を調べて、勢力選択中に領地を右クリックしても、出撃画面を表示しないようにします。
```
if (this.NowSituation == Situation.SelectGroup)
{
    return; //勢力選択中は出撃しない。
}
var cast = (Button)sender;
if (cast.Tag is not ClassPowerAndCity)
{
    return;
}
```
これで、領地以外を右クリックした時と同じく、前の画面に「戻る」動作になります。

#### 勢力選択時に中立領地を左クリックするとエラー終了するバグ

勢力選択時に特定の領地（中立領地）をクリックすると強制終了されます。
ワールドマップ上でどの領地が中立なのか識別不能なので、初めての人は唖然とするかも。

どうやら、画像読み込み時にマスターの顔グラが存在しないからのようです。
で、中立領地はマスターが設定されてないから、エラーになる訳です。
そもそも、中立領地をクリックして勢力情報画面を表示するのが変なので、表示しなければいい。

解決方法の案を書いておきます。参考にしてください。
```
private void DisplayPowerSelection(object sender)
```
関数の最初の所
```
var cast = (Button)sender;
if (cast.Tag is not ClassPowerAndCity)
{
    return;
}
```
の直後に、
```
var classPowerAndCity = (ClassPowerAndCity)cast.Tag;
```
という後の方にあった行を移動させて、
```
var cast = (Button)sender;
if (cast.Tag is not ClassPowerAndCity)
{
    return;
}

var classPowerAndCity = (ClassPowerAndCity)cast.Tag;
if (classPowerAndCity.ClassPower.MasterTag == string.Empty)
{
    return; //選択領地のマスター名が空なら、勢力情報画面を表示しない。
}
```
とします。比較項目は他のでもよさそう。中立かどうかさえ分かればいいです。
これで、中立領地を左クリックしても勢力情報画面は表示されず、エラーも発生しなくなります。

**Comment by fluffySheepInX** [comment]
修正させて頂きました！ありがとうございます！うおおおおお！！
