### ISSUE TITLE
識別名を Contains で比較してる問題

### ISSUE THREAD

**Issue by Yutaka-Sawada** [fluffySheepInX/WPF_Successor_001_to_Vahren#32]
Page001_Conscription.xaml.cs において
ユニットの識別名を比較する箇所で Contains （部分一致）を使うと
似たような名前のクラスを混同してしまう危険性があります。
63行目と 399行目と、529行目です。

Win010_TestBattle.xaml.cs において、
戦場に配置するユニットの識別名に Contains を使ってます。
59行目と 80行目です。

MainWindow.xaml.cs
1048行目
```
var result = this.ClassGameStatus.AllListSpot.Where(x => x.ListMember.Contains(new(classPowerAndCity.ClassPower.MasterTag, 0))).FirstOrDefault();
```
がうまく動いてないようです。
Linqの事はよく分からないんですが、
マスターの識別名を初期メンバーに含む領地を探してるはずですが、
なぜかマスター所在地を取得できてません。
```
var result = this.ClassGameStatus.AllListSpot.Where(x => x.ListMember.Contains(new(classPowerAndCity.ClassPower.MasterTag, 1))).FirstOrDefault();
```
に書き変えたら、ちゃんと取得できるようになりました。
データの構造的に、人数も指定しないと駄目だったのかも。

ゲーム開始時に領地にユニットを配置する際に
識別名を比較しようと Contains を使ってます。
1392行目と 1412行目です。

識別名を比較する時の Equals と == の違いはよく分かりません。
とりあえず、Contains は使わない方が良さそうです。
修正お願いします。

**Comment by fluffySheepInX** [comment]
修正しました！イシューありがとうございました！
