### ISSUE TITLE
フルスクリーン（全画面表示）でゲームを開始する方法

### ISSUE THREAD

**Issue by Yutaka-Sawada** [fluffySheepInX/WPF_Successor_001_to_Vahren#4]
C# WPF の仕様が謎だったんですが、いろいろ試してなんとなく分かりました。
ウインドウを最大化して枠を消すと、フルスクリーンになるようです。
ディスプレイ画面全体に広がります。タスクバーは隠れます。

一方で、ウインドウ枠を表示したまま最大化すると、作業領域に広がるので、
タスクバーが表示されたままになります。
以前報告した「タスクバー表示の問題」はフルスクリーンなら発生しません。

ゲームするだけならフルスクリーンの方がいいんですが、
デバッグ中はウインドウ表示の方が便利なことが多いです。
それで、[「WPFで画面を全画面表示する」](https://www.paveway.info/entry/2020/09/11/wpf_fullscreen)というページを参考にして、
F11キーで状態を切り替るコードを書いてみました。
ゲーム中に、ESCキーで終了、F11キーでフルスクリーン切り替えします。

あと、UIのずれを解消するため、ウインドウを最大化してるかどうかで、
キャンバスの位置も調節するようにしました。
最大化・フルスクリーン中なら、画面の中央にキャンバスを置き、
ウインドウ表示なら左上に合わせます。

変更するファイルは MainWindow.xaml と MainWindow.xaml.cs です。
以下に詳細を書いておきます。参考にしてください。

MainWindow.xaml のウインドウサイズ指定ですが、現在の
```
Height="300"
Width="300"
```
だと値が小さすぎるので、大きくして、最小サイズと位置も設定しました。
```
Height="1000"
Width="1800"
MinHeight="1000"
MinWidth="1800"
Top="0"
Left="0"
```
ウインドウの初期設定時にコードで設定してもいいんですが、
現在はキャンバスサイズが 1800x1000 に固定されてるっぽいので、
xaml に直接書きました。将来的には改善した方がよさそう。

MainWindow.xaml.cs の MainWindow_Initialized 関数の最初の所、現在は
```
//this.WindowStyle = WindowStyle.None;
this.WindowState = WindowState.Maximized;
```
というふうに最大化してるけどウインドウ枠を残してるので、コメントを外します。
```
// 初期状態でフルスクリーンにする。F11キーを押すとウインドウ表示になる。
this.WindowStyle = WindowStyle.None;
this.WindowState = WindowState.Maximized;
// ウインドウ表示で始めたい場合は、上をコメントアウトして、下のコメントを解除する。
//this.WindowStyle = WindowStyle.SingleBorderWindow;
//this.WindowState = WindowState.Normal;
```
これで初期状態がフルスクリーン表示になります。
いちおう、ウインドウ表示で始めたい場合のコードも書いてます。

次に、キャンバスのマージンはウインドウ状態に応じて変更するので、
MainWindow_ContentRendered 関数においてマージン設定してる部分を消します。
```
this.canvasMain.Margin = new Thickness()
{
    Top = (this._sizeClientWinHeight / 2) - (this.CanvasMainHeight / 2),
    Left = (this._sizeClientWinWidth / 2) - (this.CanvasMainWidth / 2),
};
this.WindowStyle = WindowStyle.SingleBorderWindow;
```
WindowStyle を指定してる部分も消してください。
MainWindow_Initialized 関数で指定済みですから。

そして、F11キーに反応するコードを書きます。
MainWindow_KeyDown 関数内で ESCキーに反応してる部分があります。
```
if (e.Key == Key.Escape)
{
    this.Close();
}
```
この下に追加してください。
```
// ESCキーを押すと終了する。
if (e.Key == Key.Escape)
{
    this.Close();
}
// F11キーを押すとフルスクリーン状態を切り替える。
else if (e.Key == Key.F11)
{
    if (WindowState == WindowState.Maximized)
    {
        // 最大化中なら、通常サイズにする。
        this.WindowStyle = WindowStyle.SingleBorderWindow; // タイトルバーと境界線を表示します。
        this.WindowState = WindowState.Normal;
    }
    else
    {
        // 通常サイズか最小化中なら、最大化する。
        this.WindowStyle = WindowStyle.None; // タイトルバーと境界線を非表示にします。
        this.WindowState = WindowState.Maximized;
    }
}
```

最後に、
フルスクリーン、最大化ウインドウ、通常ウインドウの三種類に対応するため
canvasTop_SizeChanged 関数にマージンを調節するコードを追加します。
現在の
```
// クライアント領域を知る方法
var si = e.NewSize;
this._sizeClientWinWidth = (int)si.Width;
this._sizeClientWinHeight = (int)si.Height;
```
という部分の下に追加してください。（上だと変数が更新されてない）
```
// クライアント領域を知る方法
var si = e.NewSize;
this._sizeClientWinWidth = (int)si.Width;
this._sizeClientWinHeight = (int)si.Height;

if (this.WindowState == WindowState.Maximized)
{
    // 最大化中なら、キャンバスをフルスクリーンの中央に置く。
    this.canvasMain.Margin = new Thickness()
    {
        Top = (this._sizeClientWinHeight / 2) - (this.CanvasMainHeight / 2),
        Left = (this._sizeClientWinWidth / 2) - (this.CanvasMainWidth / 2)
    };
}
else
{
    // 通常サイズか最小化中なら、キャンバスをウインドウの左上位置に置く。
    this.canvasMain.Margin = new Thickness()
    {
        Top = 0, Left = 0
    };
}
```
クライアント領域のサイズを取得した後に、キャンバス位置を更新します。

**Comment by fluffySheepInX** [comment]
対応させて頂きました！ありがとうございます！
