### ISSUE TITLE
内政の仕様について

### ISSUE THREAD

**Issue by fluffySheepInX** [fluffySheepInX/WPF_Successor_001_to_Vahren#68]
内政の仕様について、以下は如何でしょうか。
```
都市の新しい仕様の構造体
NewFormatSpot spot0009
{

	name = "ハラーハッフ";
	image = "099_SNOW2.png";
	x = "2800";
	y = "680";
	map = "wefwefwefwefw";
	capacity = "6";
	member = "LineInfantryM14*2,DragoonFrancesca,HowitzerC11";
	text = "短い文章です。";
	
	# 実行出来る内政をinternalAffairsタグで指定
	internalAffairs = "abc,def,ghi";
}
```

```
internalAffairsDetail abc
{

	# 画面上に表示される名前
	title = "物流改善";
	
	# 100px*512pxで画面上に表示
	image = "abc.png";

	# 前提とする内政（これが実行されてなければ、この内政は実行不可能
	premise = "def";
	# 前提とする内政の必要回数（5なら5回実行が必要
	premiseNumber = "3";
	
	# 収入補正
	# %分、上昇する
	# -1だと実行されない
	incomeCorrection = "0.5";
	
	# 収入
	# 数値分、上昇する
	# -1だと実行されない
	income = "1000";
	
	# スキル付与(出撃時と防衛時、全部隊に
	# スキルのタグを指定する
	# -1だと実行されない
	skill = "gun01";
	
	# ユニット追加(出撃時と防衛時、操作不可、自動で移動と攻撃
	unit = "LineInfantryM14*2";
	
	# 上昇させる能力値
	# -1だと実行されない
	ability = "power";

	# 能力値上昇をさせる時(出撃時と防衛時どちらか
	# -1だと実行されない
	abilityTiming = "Sortie";
	
	# 能力値上昇値
	# -1だと実行されない
	abilityUp = "5";
}
```

画面UI
![内政](https://user-images.githubusercontent.com/106497609/209482898-ddf6086d-d1ae-4056-ba61-23ea6386922b.JPG)

**Comment by fluffySheepInX** [comment]
画面UIは実際にはもっとオシャンティーにするつもりです。
あくまで配置はこんな感じみたいにお考え下さい。

**Comment by Yutaka-Sawada** [comment]
ヴァーレンの内政システムは内政領地にボタン（ユニット）が並んで、
それぞれの雇用ウィンドウで選択だから、いまいち使い勝手が悪いです。

勢力ウィンドウで「内政ボタン」をクリックする。-> 内政ウィンドウが出現する。
内政ウィンドウで「内政領地のボタン」をクリックする。 -> 内政領地が出現する。
内政領地で「内政ユニット」をクリックする。-> 選択可能な内政項目が表示される。
一覧から「内政項目」をクリックする。-> その内政処理が実行される。
という風に、目的を達成するまでのクリック回数が多いのが問題です。
どこにどんな項目があるかも分かりにくい。

内政に凝ってるオリシナの内政画面構成を例としてアップしときます。
別々のウィンドウに個別に表示されるので、全体像を把握しにくい。

![内政ウィンドウの例](https://user-images.githubusercontent.com/60930312/209499304-e0eb38fb-769a-4f49-9fe7-d165cce3e580.png)

同じ勢力ウィンドウの上で一覧表示と選択できる点で、提案されたUIは良いと思います。
RPGのスキルツリーとか、シビライゼーションの技術開発ツリー、みたいな感じかな。

ただ、選択肢が多いと一画面に収まらないことが問題点になるかもしれません。
スクロールで一部だけ表示だと、一画面にする意味が薄れるし。

昔はタブメニューが一般的でしたが、タブの数が多いと何列にもなって逆に分かりにくいです。
今はツリービューを利用したメニューがいいかも。必要に応じて、ツリーを開いたり閉じたりできるやつ。
![ツリーメニューの例](https://user-images.githubusercontent.com/60930312/209499318-02af64ee-706a-4f82-81a1-abef73da57df.png)

**Comment by fluffySheepInX** [comment]
掲示板より

毎ターンユニットを生産するとか、未行動ユニットのステ上昇させるとか
スポットの特性というと砂漠や雪山に居座ってるとデバフが追加されていくとか
地形が移動速度と突撃可否ぐらいしか影響ないし雪原で無条件に強くなるアイスマンなど

**Comment by fluffySheepInX** [comment]
参考サイト
https://anderson02.com/cs/wpf/wpf-23/

**Comment by fluffySheepInX** [comment]
基本的な部分を実装したのでクローズ
また、help,costを追加しました
