### ISSUE TITLE
既存の Page を UserControl に変更する方法

### ISSUE THREAD

**Issue by Yutaka-Sawada** [fluffySheepInX/WPF_Successor_001_to_Vahren#9]
ナビゲーション機能を使ってないので、
Page005_StrategyMenu を Page から UserControl に変えてみました。

まず Page005_StrategyMenu.xaml ファイルの 1行目と 80行目の
`<Page` ~ `</Page>` という部分を
`<UserControl` ~ `</UserControl>` に書き変えます。
あと、独立した子ウインドウではなくなるので
```
Title="Page005_StrategyMenu"
Background="Transparent"
```
という行を消します。

次に Page005_StrategyMenu.xaml.cs ファイルの 21行目の
```
public partial class Page005_StrategyMenu : Page
```
という行の最後を書き変えて
```
public partial class Page005_StrategyMenu : UserControl
```
にします。

これで、Visual Studio から UserControl として認識されるようになり、
xaml デザイナーでも正しく表示されます。

最後に MainWindow.xaml.cs ファイルの SetWindowStrategyMenu 関数において
Frame に Page を追加してた部分
```
frame.Navigate(this.ClassGameStatus.WindowStrategyMenu);
frame.Margin = new Thickness()
{
    Left = this.canvasUIRightBottom.Width - widthCanvas,
    Top = this.canvasUIRightBottom.Height - HeightCanvas
};
frame.Name = StringName.canvasWindowStrategy;
this.canvasUIRightBottom.Children.Add(frame);
```
ここを frame を使わずに、直接 UserControl を追加します。
```
this.ClassGameStatus.WindowStrategyMenu.Margin = new Thickness()
{
    Left = this.canvasUIRightBottom.Width - widthCanvas,
    Top = this.canvasUIRightBottom.Height - HeightCanvas
};
this.canvasUIRightBottom.Children.Add(this.ClassGameStatus.WindowStrategyMenu);
```
こちらの方がシンプルです。

不要になった
```
//TODO https://yudachi-shinko.blogspot.com/2019/09/wpfframepage.html
while (frame.CanGoBack)
{
    frame.RemoveBackEntry();
}
```
という箇所は削除します。

他のナビゲーション要素として使われてない Page も、同様に UserControl に変更できそうです。

**Comment by fluffySheepInX** [comment]
全てのPageをUserControlに置き換えたらこのイシューを閉じます～
ありがとうございます～

**Comment by fluffySheepInX** [comment]
対応完了しました。
